### ISSUE TITLE
poppler-utils missing

### ISSUE THREAD

**Issue by bgold0** [fagbokforlaget/pdfinfojs#5]
I get the following error:

> Error: pdfinfo (poppler-utils) is missing. Hint: sudo apt-get install poppler-utils at /../node_modules/pdfinfojs/lib/pdfinfo.js:57:17 at /../node_modules/shelljs/src/exec.js:204:9 at ChildProcess.exithandler (child_process.js:212:5) at emitTwo (events.js:106:13) at ChildProcess.emit (events.js:194:7) at maybeClose (internal/child_process.js:899:16) at Socket. (internal/child_process.js:342:11) at emitOne (events.js:96:13) at Socket.emit (events.js:191:7) at Pipe._handle.close [as _onclose] (net.js:511:12)

Anyone know how I can solve this?

This is my code:

    var pdf = new pdfinfo('/tmp/template.pdf');

    pdf.getInfo(function(err, info, params) {
     if (err) { console.log(err.stack); }
    else { console.log{info:info,params:params});  }

**Comment by iapain** [comment]
Its simply saying poppler util is missing, which OS you are on?
